version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=hotel_booking
      - DB_USER=hotel_user
      - DB_PASSWORD=hotel_password
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=hotel_booking
      - POSTGRES_USER=hotel_user
      - POSTGRES_PASSWORD=hotel_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 